HotelManagementSystem/Entities/Service.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace HotelManagementSystem.ViewModels
{
    public class Service
    { 
        [Key]
        public Guid ServiceId {get; set;}

        [Required]
        [MaxLength(60)]   
        public string Name {get; set;}      
        
        [MaxLength(600)]   
        public string? Info {get; set;}    

        [Required(ErrorMessage = "Please enter the correct price")]
        [Range(0.5, double.MaxValue,ErrorMessage ="Price should be larger than 0.5$")]
        public double Price {get; set;}    

        [Required(ErrorMessage = "Please select the service type")]
        public int ServiceTypeId { get; set; }
        public ServiceType ServiceType { get; set; }

        [JsonIgnore]
        public List<EnrollmentService> EnrollmentServices { get; set; }
    }
}

HotelManagementSystem/Entities/ServiceType.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace HotelManagementSystem.ViewModels
{
    public class ServiceType
    {
        [Key]
        public int ServiceId {get; set;}

        [Required(ErrorMessage = "Please enter the name for service type")]
        [MaxLength(50)]
        public string TypeName {get; set;}

        [JsonIgnore]
        public List<Service> Services {get; set; }
    }
}

HotelManagementSystem/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotelManagementSystem.Data;
using HotelManagementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace HotelManagementSystem
{
    [Authorize]
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ServicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Services
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Services.Include(s => s.ServiceType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.ServiceType)
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            ViewData["ServiceTypeId"] = new SelectList(_context.ServiceTypes, "ServiceId", "TypeName");
            return View();
        }

        // POST: Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,Name,Info,Price,ServiceTypeId")] Service service)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ServiceTypeId"] = new SelectList(_context.ServiceTypes, "ServiceId", "TypeName", service.ServiceTypeId);
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            ViewData["ServiceTypeId"] = new SelectList(_context.ServiceTypes, "ServiceId", "TypeName", service.ServiceTypeId);
            return View(service);
        }

        // POST: Services/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ServiceId,Name,Info,Price,ServiceTypeId")] Service service)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            ModelState.Clear();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.ServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ServiceTypeId"] = new SelectList(_context.ServiceTypes, "ServiceId", "TypeName", service.ServiceTypeId);
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.ServiceType)
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Services == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Services'  is null.");
            }
            var service = await _context.Services.FindAsync(id);
            if (service != null)
            {
                _context.Services.Remove(service);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(Guid id)
        {
          return (_context.Services?.Any(e => e.ServiceId == id)).GetValueOrDefault();
        }
    }
}

HotelManagementSystem/Views/Services/Create.cshtml
@model HotelManagementSystem.ViewModels.Service

@{
    ViewData["Title"] = "Create";
}

<section class="full-height">
    <div class="row form-row">
        <div class="col-md-10">
            <div class="container-border p-3 mt-4 mb-4">
                <div class="container-body">
                    <h3 class="mb-2 pt-2 text-center">Create New Service</h3>
                    <hr />
                    <div id="t_list" class="p-3">
                        <form asp-action="Create" asp-controller="Services">
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-4">
									<div asp-validation-summary="ModelOnly" class="text-danger"></div>
									<div class="form-floating mb-3">
                                        <input asp-for="Name" class="form-control" />
                                        <label asp-for="Name" class="control-label"></label>
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <textarea asp-for="Info" class="form-control" style="height: 140px"></textarea>
										<label asp-for="Info" class="control-label"></label>
                                        <span asp-validation-for="Info" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
									    <input asp-for="Price" type="number" step="0.01" class="form-control" />
									    <label asp-for="Price" class="control-label"></label>
									    <span asp-validation-for="Price" class="text-danger"></span>
								    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ServiceTypeId" class="form-control" asp-items="ViewBag.ServiceTypeId"></select>
                                        <label asp-for="ServiceTypeId" class="control-label"></label>
                                        <span asp-validation-for="ServiceTypeId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-1"></div>
                            </div>
                            <div class="centered-content mt-5 mb-3">
                                <a asp-action="Index" class="btn btn-danger me-3 w-25">Back</a>
                                <input type="submit" value="Save" class="btn btn-success w-25"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelManagementSystem/Views/Services/Edit.cshtml
@model HotelManagementSystem.ViewModels.Service

@{
    ViewData["Title"] = "Edit";
}


<section class="full-height">
    <div class="row form-row">
        <div class="col-md-10">
            <div class="container-border p-3 mt-4 mb-4">
                <div class="container-body">
                    <h3 class="mb-2 pt-2 text-center">Edit Service</h3>
                    <hr />
                    <div id="t_list" class="p-3">
                        <form asp-action="Edit" asp-controller="Services">
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-4">
									<div asp-validation-summary="ModelOnly" class="text-danger"></div>
									<input type="hidden" asp-for="ServiceId" />
                                    <div class="form-floating mb-3">
                                        <input asp-for="Name" class="form-control" />
                                        <label asp-for="Name" class="control-label"></label>
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <textarea asp-for="Info" class="form-control" style="height: 140px"></textarea>
										<label asp-for="Info" class="control-label"></label>
                                        <span asp-validation-for="Info" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
									    <input asp-for="Price" type="number" step="0.01" class="form-control" />
									    <label asp-for="Price" class="control-label"></label>
									    <span asp-validation-for="Price" class="text-danger"></span>
								    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ServiceTypeId" class="form-control" asp-items="ViewBag.ServiceTypeId"></select>
                                        <label asp-for="ServiceTypeId" class="control-label"></label>
                                        <span asp-validation-for="ServiceTypeId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-1"></div>
                            </div>
                            <div class="centered-content mt-5 mb-3">
                                <a asp-action="Index" class="btn btn-primary me-3 w-25">Back</a>
                                <input type="submit" value="Save" class="btn btn-success w-25"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelManagementSystem/Views/Services/Index.cshtml
@model IEnumerable<HotelManagementSystem.ViewModels.Service>

@{
    ViewData["Title"] = "Index";
}

<div class="full-height transparent-block">
    
    <div class="pt-2 pb-2 control-row">
        <h3 class="text-center" style=" margin-bottom:-30px;">Apartments</h3>
        <a asp-controller="Index" asp-action="Index" class="btn btn-primary leaned-left">Back</a>
        <a asp-action="Create" class="btn btn-success leaned-right">Create</a>
    </div>

    <div class="row form-row">
        <div class="col-md-12">
            <div id="t_list" class="entities-grid-container p-3">
                <ejs-grid id="entities_grid" dataSource="@Model" allowGrouping="false" allowSorting="true" allowFiltering="true" 
                          allowPaging="false" allowSelection="true" excelExportComplete="excelExportComplete" 
                          allowExcelExport="true" created="entities_grid_created" toolbarClick="toolbarClick" gridLines="Both"
                          toolbar="@(new List<string>() {"ExcelExport"})"  >
                    <e-grid-groupsettings columns="@(new string[] {"Date"})" showUngroupButton="false" showGroupedColumn="true"></e-grid-groupsettings>
                    <e-grid-filtersettings mode="Immediate" showFilterBarOperator="true" type="Excel" showFilterBarStatus="true"></e-grid-filtersettings>
                    <e-grid-pagesettings pageSize="20"></e-grid-pagesettings>
                    <e-grid-columns>
                        <e-grid-column headerText="Name" field="Name" textAlign="Center" width="150px"></e-grid-column>
                        <e-grid-column headerText="Info" field="Info" textAlign="Center" width="200px"></e-grid-column>
                        <e-grid-column headerText="Price" field="Price" textAlign="Center" width="140px"></e-grid-column>
                        <e-grid-column headerText="Type" field="ServiceType.TypeName" textAlign="Center" width="100px"></e-grid-column>
                        <e-grid-column headerText="Actions" template="#actionColumnTemplate" textAlign="Center" width="80px"></e-grid-column>
                    </e-grid-columns>
                </ejs-grid>
            </div>
        </div>
    </div>

</div>




<script id="actionColumnTemplate" type="text/x-template">
    <div class="d-flex flex-row justify-content-start edit-block">
        <a class="btn btn-sm no-a-decoration" href="/Services/Edit/${ServiceId}">
            <i class="fa-solid fa-pen fa-lg"></i>
        </a>
        <form action="/Services/Delete/${ServiceId}" method="post">
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-sm btn-link no-a-decoration"
            onclick="return confirm(&quot;Are sure to delete this record?&quot;)">
                <i class="fa-solid fa-trash-can fa-lg"></i>
            </button>
        </form>
    </div>
</script>

<script>
    function toolbarClick(args) {
        var gridObj = document.getElementById("entities_grid").ej2_instances[0];
        if (args.item.id === 'entities_grid_excelexport') {
            //this.columns[3].visible = false;
            gridObj.showSpinner();
            gridObj.excelExport();
        }
    }

    function excelExportComplete(args) {
        this.hideSpinner();
    }
</script>

<script>
    function before_export(parameters) {
        var gridObj = document.getElementById("entities_grid").ej2_instances[0];
        gridObj.setAttribute("allowGrouping","false");
    }
</script>

<script>
    function entities_grid_created() {
        var toolbar = this.element.querySelector('.e-toolbar');
        this.element.appendChild(toolbar);
    }
</script>