HotelManagementSystem/Entities/Apartment.cs
using System.ComponentModel.DataAnnotations;

namespace HotelManagementSystem.ViewModels
{
    public class Apartment
    {
        [Key]
        public Guid ApartmentId {get; set;}

        [MaxLength(30)]
        [Required(ErrorMessage = "Number is necessary")]
        public string ApartmentName {get; set;}

        [MaxLength(30)]
        [Required(ErrorMessage = "Title is necessary")]
        public string ApartmentTitle {get; set;}

        [MaxLength(120)]
        public string? Description {get; set;}

        public string? ImageUrl {get; set;} = string.Empty;

        [Required(ErrorMessage = "Please enter the correct price")]
        [Range(5.0, double.MaxValue,ErrorMessage = "Price should be larger than 5$")]
        public double DailyPrice {get; set;}

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select Apartment Type")]
        public int ApartmentTypeId {get; set;}
        public ApartmentType ApartmentType {get; set;}

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select Apartment Category")]
        public int ApartmentCategoryId {get; set;}
        public ApartmentCategory ApartmentCategory {get; set;}

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select Apartment Status")]
        public int ApartmentStatusId {get; set;}
        public ApartmentStatus ApartmentStatus {get; set;}
    }
}

HotelManagementSystem/Entities/ApartmentType.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace HotelManagementSystem.ViewModels
{
    public class ApartmentType
    {
        [Key]
        public int ApartmentTypeId {get; set;}
        
        [Required]
        [MaxLength(30)]
        public string TypeName {get; set;}

        [JsonIgnore]
        public List<Apartment> Apartments {get; set; }
    }
}

HotelManagementSystem/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotelManagementSystem.Data;
using HotelManagementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace HotelManagementSystem.Controllers
{
    [Authorize]
    public class ApartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Apartment
        public async Task<IActionResult> Index()
        {
            var aplist = _context.Apartments
                .Include(a => a.ApartmentCategory)
                .Include(a => a.ApartmentStatus)
                .Include(a => a.ApartmentType);

            return View(await aplist.OrderBy(t => t.ApartmentName).ToListAsync());
        }

        // GET: Apartment/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Apartments == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartments
                .Include(a => a.ApartmentCategory)
                .Include(a => a.ApartmentStatus)
                .Include(a => a.ApartmentType)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (apartment == null)
            {
                return NotFound();
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        public IActionResult Create()
        {
            ViewData["ApartmentCategoryId"] = new SelectList(
                _context.ApartmentCategories, "ApartmentCategoryId", "CategoryName");
            ViewData["ApartmentStatusId"] = new SelectList(
                _context.ApartmentStatuses, "ApartmentStatusId", "StatusName");
            ViewData["ApartmentTypeId"] = new SelectList(
                _context.ApartmentTypes, "ApartmentTypeId", "TypeName");
            return View();
        }

        // POST: Apartments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ApartmentId,ApartmentName,ApartmentTitle,Description,ImageUrl,DailyPrice,ApartmentTypeId,ApartmentCategoryId,ApartmentStatusId")] Apartment apartment)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                _context.Add(apartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApartmentCategoryId"] = new SelectList(
                _context.ApartmentCategories, "ApartmentCategoryId", "CategoryName", apartment.ApartmentCategoryId);
            ViewData["ApartmentStatusId"] = new SelectList(
                _context.ApartmentStatuses, "ApartmentStatusId", "StatusName", apartment.ApartmentStatusId);
            ViewData["ApartmentTypeId"] = new SelectList(
                _context.ApartmentTypes, "ApartmentTypeId", "TypeName", apartment.ApartmentTypeId);
            return View(apartment);
        }

        // GET: Apartments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Apartments == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartments.FindAsync(id);
            if (apartment == null)
            {
                return NotFound();
            }
            ViewData["ApartmentCategoryId"] = new SelectList(
                _context.ApartmentCategories, "ApartmentCategoryId", "CategoryName", apartment.ApartmentCategoryId);
            ViewData["ApartmentStatusId"] = new SelectList(
                _context.ApartmentStatuses, "ApartmentStatusId", "StatusName", apartment.ApartmentStatusId);
            ViewData["ApartmentTypeId"] = new SelectList(
                _context.ApartmentTypes, "ApartmentTypeId", "TypeName", apartment.ApartmentTypeId);
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, [Bind] Apartment apartment)
        {
            if (id != apartment.ApartmentId)
            {
                return NotFound();
            }

            ModelState.Clear();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(apartment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApartmentExists(apartment.ApartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApartmentCategoryId"] = new SelectList(
                _context.ApartmentCategories, "ApartmentCategoryId", "CategoryName", apartment.ApartmentCategoryId);
            ViewData["ApartmentStatusId"] = new SelectList(
                _context.ApartmentStatuses, "ApartmentStatusId", "StatusName", apartment.ApartmentStatusId);
            ViewData["ApartmentTypeId"] = new SelectList(
                _context.ApartmentTypes, "ApartmentTypeId", "TypeName", apartment.ApartmentTypeId);
            return View(apartment);
        }

        // GET: Apartments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Apartments == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartments
                .Include(a => a.ApartmentCategory)
                .Include(a => a.ApartmentStatus)
                .Include(a => a.ApartmentType)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (apartment == null)
            {
                return NotFound();
            }

            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Apartments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Apartments' is null.");
            }
            var apartment = await _context.Apartments.FindAsync(id);
            if (apartment != null)
            {
                _context.Apartments.Remove(apartment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApartmentExists(Guid id)
        {
          return (_context.Apartments?.Any(e => e.ApartmentId == id)).GetValueOrDefault();
        }
    }
}

HotelManagementSystem/Views/Apartments/Create.cshtml
@model HotelManagementSystem.ViewModels.Apartment

@{
    ViewData["Title"] = "Create";
}


<section class="full-height">
    <div class="row form-row">
        <div class="col-md-10">
            <div class="container-border p-3 mt-4 mb-4">
                <div class="container-body">
                    <h3 class="mb-2 pt-2 text-center">Create Apartment</h3>
                    <hr />
                    <div id="t_list" class="p-3">
                        <form asp-action="Create" asp-controller="Apartments">
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-4">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ApartmentTitle" class="form-control" />
                                        <label asp-for="ApartmentTitle" class="control-label"></label>
                                        <span asp-validation-for="ApartmentTitle" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ApartmentName" class="form-control" />
                                        <label asp-for="ApartmentName" class="control-label"></label>
                                        <span asp-validation-for="ApartmentName" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ImageUrl" class="form-control" />
                                        <label asp-for="ImageUrl" class="control-label"></label>
                                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <textarea asp-for="Description" class="form-control" placeholder="Description" style="height: 140px"></textarea>
                                        <label asp-for="Description" class="control-label"></label>
                                        <span asp-validation-for="Description" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input asp-for="DailyPrice" type="number" step="0.01" class="form-control" />
                                        <label asp-for="DailyPrice" class="control-label"></label>
                                        <span asp-validation-for="DailyPrice" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentTypeId" class="form-select" asp-items="ViewBag.ApartmentTypeId"></select>
                                        <label asp-for="ApartmentTypeId" class="control-label"></label>
                                        <span asp-validation-for="ApartmentTypeId" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentCategoryId" class="form-select" asp-items="ViewBag.ApartmentCategoryId"></select>
                                        <label asp-for="ApartmentCategoryId" class="control-label"></label>
                                        <span asp-validation-for="ApartmentCategoryId" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentStatusId" class="form-select" asp-items="ViewBag.ApartmentStatusId"></select>
                                        <label asp-for="ApartmentStatusId" class="control-label"></label>
                                        <span asp-validation-for="ApartmentStatusId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-1"></div>
                            </div>
                            <div class="centered-content mt-5 mb-3">
                                <a asp-action="Index" class="btn btn-primary me-3 w-25">Back</a>
                                <input type="submit" value="Create" class="btn btn-success w-25"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelManagementSystem/Views/Apartments/Edit.cshtml
@model HotelManagementSystem.ViewModels.Apartment

@{
    ViewData["Title"] = "Edit";
}

<section class="full-height">
    <div class="row form-row">
        <div class="col-md-10">
            <div class="container-border p-3 mt-4 mb-4">
                <div class="container-body">
                    <h3 class="mb-2 pt-2 text-center">Edit Apartment</h3>
                    <hr />
                    <div id="t_list" class="p-3">
                        <form asp-action="Edit" asp-controller="Apartments">
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-4">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <input type="hidden" asp-for="ApartmentId"/>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ApartmentTitle" class="form-control" />
                                        <label asp-for="ApartmentTitle" class="control-label">Title</label>
                                        <span asp-validation-for="ApartmentTitle" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ApartmentName" class="form-control" />
                                        <label asp-for="ApartmentName" class="control-label">Number</label>
                                        <span asp-validation-for="ApartmentName" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input asp-for="ImageUrl" class="form-control" />
                                        <label asp-for="ImageUrl" class="control-label">Image Url</label>
                                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <textarea asp-for="Description" class="form-control" placeholder="Description" style="height: 140px"></textarea>
                                        <label asp-for="Description" class="control-label">Description</label>
                                        <span asp-validation-for="Description" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input asp-for="DailyPrice" type="number" step="0.01" class="form-control" />
                                        <label asp-for="DailyPrice" class="control-label">Daily Price</label>
                                        <span asp-validation-for="DailyPrice" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentTypeId" class="form-select" asp-items="ViewBag.ApartmentTypeId"></select>
                                        <label asp-for="ApartmentTypeId" class="control-label">Apartment Type</label>
                                        <span asp-validation-for="ApartmentTypeId" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentCategoryId" class="form-select" asp-items="ViewBag.ApartmentCategoryId"></select>
                                        <label asp-for="ApartmentCategoryId" class="control-label">Apartment Category</label>
                                        <span asp-validation-for="ApartmentCategoryId" class="text-danger"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <select asp-for="ApartmentStatusId" class="form-select" asp-items="ViewBag.ApartmentStatusId"></select>
                                        <label asp-for="ApartmentStatusId" class="control-label">Apartment Status</label>
                                        <span asp-validation-for="ApartmentStatusId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-1"></div>
                            </div>
                            <div class="centered-content mt-5 mb-3">
                                <a asp-action="Index" class="btn btn-primary me-3 w-25">Back</a>
                                <input type="submit" value="Save" class="btn btn-success w-25"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelManagementSystem/Views/Apartments/Index.cshtml
@model IEnumerable<HotelManagementSystem.ViewModels.Apartment>

@{
    ViewData["Title"] = "Index";
}


<div class="full-height transparent-block">
    
    <div class="pt-2 pb-2 control-row">
        <h3 class="text-center" style=" margin-bottom:-30px;">Apartments</h3>
        <a asp-controller="Index" asp-action="Index" class="btn btn-primary leaned-left">Back</a>
        <a asp-action="Create" class="btn btn-success leaned-right">Create</a>
    </div>

    <div class="row form-row">
        <div class="col-md-12">
            <div id="t_list" class="entities-grid-container p-3">
                <ejs-grid id="entities_grid" dataSource="@Model" allowGrouping="false" allowSorting="true" allowFiltering="true" 
                          allowPaging="false" allowSelection="true" excelExportComplete="excelExportComplete" 
                          allowExcelExport="true" created="entities_grid_created" toolbarClick="toolbarClick" gridLines="Both"
                          toolbar="@(new List<string>() {"ExcelExport"})"  >
                    <e-grid-groupsettings columns="@(new string[] {"Date"})" showUngroupButton="false" showGroupedColumn="true"></e-grid-groupsettings>
                    <e-grid-filtersettings mode="Immediate" showFilterBarOperator="true" type="Excel" showFilterBarStatus="true"></e-grid-filtersettings>
                    <e-grid-pagesettings pageSize="20"></e-grid-pagesettings>
                    <e-grid-columns>
                        <e-grid-column headerText="ID" field="ApartmentId" textAlign="Center" width="280px"></e-grid-column>
                        <e-grid-column headerText="Title" field="ApartmentTitle" textAlign="Center" width="150px"></e-grid-column>
                        <e-grid-column headerText="Number" field="ApartmentName" textAlign="Center" width="120px"></e-grid-column>
                        <e-grid-column headerText="Image URL" field="ImageUrl" textAlign="Center" width="130px"></e-grid-column>
                        <e-grid-column headerText="Daily Price" field="DailyPrice" textAlign="Center" width="130px"></e-grid-column>
                        <e-grid-column headerText="Type" field="ApartmentType.TypeName" textAlign="Center" width="110px"></e-grid-column>
                        <e-grid-column headerText="Category" field="ApartmentCategory.CategoryName" textAlign="Center" width="120px"></e-grid-column>
                        <e-grid-column headerText="Status" field="ApartmentStatus.StatusName" textAlign="Center" width="100px"></e-grid-column>
                        <e-grid-column headerText="Actions" template="#actionColumnTemplate" textAlign="Center" width="100px"></e-grid-column>
                    </e-grid-columns>
                </ejs-grid>
            </div>
        </div>
    </div>

</div>




<script id="actionColumnTemplate" type="text/x-template">
    <div class="d-flex flex-row justify-content-start edit-block">
        <a class="btn btn-sm no-a-decoration" href="/Apartments/Edit/${ApartmentId}">
            <i class="fa-solid fa-pen fa-lg"></i>
        </a>
        <form action="/Apartments/Delete/${ApartmentId}" method="post">
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-sm btn-link no-a-decoration"
            onclick="return confirm(&quot;Are sure to delete this record?&quot;)">
                <i class="fa-solid fa-trash-can fa-lg"></i>
            </button>
        </form>
    </div>
</script>

<script>
    function toolbarClick(args) {
        var gridObj = document.getElementById("entities_grid").ej2_instances[0];
        if (args.item.id === 'entities_grid_excelexport') {
            //this.columns[3].visible = false;
            gridObj.showSpinner();
            gridObj.excelExport();
        }
    }

    function excelExportComplete(args) {
        this.hideSpinner();
    }
</script>

<script>
    function before_export(parameters) {
        var gridObj = document.getElementById("entities_grid").ej2_instances[0];
        gridObj.setAttribute("allowGrouping","false");
    }
</script>

<script>
    function entities_grid_created() {
        var toolbar = this.element.querySelector('.e-toolbar');
        this.element.appendChild(toolbar);
    }
</script>